export const EMAIL_INPUT = 'ADD_USER_EMAIL_INPUT';
export const PASSWORD_INPUT = 'ADD_USER_PASSWORD_INPUT';
export const PASSWORD_CONFIRM_INPUT = 'ADD_USER_PASSWORD_CONFIRM_INPUT';
export const LOGIN_INPUT = 'ADD_USER_LOGIN_INPUT';
export const PHONE_INPUT = 'ADD_USER_PHONE_INPUT';
export const DEPARTMENT_INPUT = 'ADD_USER_DEPARTMENT_INPUT';
export const SUBMIT_ADD_FORM = 'ADD_USER_SUBMIT_ADD_FORM';